main:
  - {name: About me, pageRef: /, weight: 1}
  - {name: Research, pageRef: /research, weight: 2}
  - {name: Publications, pageRef: /publications, weight: 3}
  - {name: Group, pageRef: /group, weight: 4}
  - {name: Projects, pageRef: /project, weight: 5}
  - {name: Achievements, pageRef: /achievements, weight: 6}
  - {name: Blog, pageRef: /post, weight: 7}
  - {name: Contact, pageRef: /contact, weight: 8}
